//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {

        public int Id { get; set; }
        public int IDKl { get; set; }
        public int IDAg { get; set; }
        public int IDTr { get; set; }
        public int Date { get; set; }
        public int IDGroup { get; set; }
        public List<Dogovor> DogovorList { get; set; }

        public virtual GroupDog GroupDog { get; set; }
    }
}
