//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrSl
    {
        public int Id { get; set; }
        public int IDKl { get; set; }
        public int IDDogv { get; set; }
        public System.DateTime Date { get; set; }
        public string Described { get; set; }
    }
}
