//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarif
    {
        public int Id { get; set; }
        public double Price { get; set; }
        public string Object { get; set; }
        public string Conditions { get; set; }
    }
}
